# Generated by Django 6.1.1 on 2026-09-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avito_app', '0002_category_category_name_en_category_category_name_ky_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_name_ky',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_name_ky',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='subcategory_name_ky',
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name_en',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name_ru',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
    ]
