# Generated by Django 6.1.1 on 2026-09-13 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avito_app', '0003_remove_category_category_name_ky_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='article_image',
            new_name='article_number',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_img', to='avito_app.product'),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to='avito_app.product'),
        ),
    ]
